"""Generate the PipeWire filter-chain conf from app state, and migrate the
legacy 20-rnnoise-source.conf on first run."""
import os
import re

from catalog import STAGES, STAGE_INFO, default_state

CONF_DIR = os.path.expanduser("~/.config/pipewire/pipewire.conf.d")
CONF_PATH = os.path.join(CONF_DIR, "30-clearmic.conf")
OLD_CONF = os.path.join(CONF_DIR, "20-rnnoise-source.conf")
STALE_CONF = os.path.join(CONF_DIR, "30-mic-dsp-ui.conf")  # pre-rename name

INPUT_NODE = "effect_input.rnnoise"
OUTPUT_NODE = "effect_output.rnnoise"


def _num(v):
    v = float(v)
    if v.is_integer():
        return f"{v:.1f}"
    return f"{v:.6g}"


def generate(state):
    enabled = [s for s in STAGES if state["stages"][s]["enabled"]]
    nodes_txt = []
    for s in enabled:
        info = STAGE_INFO[s]
        ctrl = state["stages"][s]["params"]
        entries = ", ".join(
            f'"{p["port"]}" {_num(ctrl[p["port"]])}'
            for p in info["params"] if p["port"] in ctrl
        )
        nodes_txt.append(
            f'            {{ type = ladspa\n'
            f'              name = {s}\n'
            f'              plugin = "{info["plugin"]}"\n'
            f'              label = "{info["label"]}"\n'
            f'              control = {{ {entries} }}\n'
            f'            }}'
        )
    links_txt = []
    for a, b in zip(enabled, enabled[1:]):
        pa = STAGE_INFO[a]["audio"]
        pb = STAGE_INFO[b]["audio"]
        links_txt.append(
            f'            {{ output = "{a}:{pa["out_l"]}" input = "{b}:{pb["in_l"]}" }}\n'
            f'            {{ output = "{a}:{pa["out_r"]}" input = "{b}:{pb["in_r"]}" }}'
        )
    desc = state.get("source_desc", "ClearMic")
    if enabled:
        desc = f"{desc} ({' + '.join(enabled)})"
    target = state.get("input", "")
    # "auto" (or empty): leave the capture stream unpinned. WirePlumber
    # then links it to the default input device and MOVES it live when
    # devices appear/disappear (bluetooth connect, HFP profile switch,
    # USB plug) - no PipeWire restart, no node.name races. Pinning is
    # kept as a manual option, but a pinned node that registers late
    # (all bluetooth mics) is not re-resolved by WirePlumber, so the
    # chain silently falls back to another source.
    capture_pin = ""
    if target and target != "auto":
        capture_pin = (f'        node.target   = "{target}"\n'
                       f'        target.object = "{target}"\n')
    nodes_joined = "\n".join(nodes_txt)
    links_joined = "\n".join(links_txt)
    return f"""\
# Generated by ClearMic. Manual edits will be overwritten.
context.modules = [
  {{ name = libpipewire-module-filter-chain
    flags = [ nofail ]
    args = {{
      node.description = "{desc}"
      media.name       = "{desc}"
      filter.graph = {{
        nodes = [
{nodes_joined}
        ]
        links = [
{links_joined}
        ]
      }}
      audio.position = [ FL FR ]
      capture.props = {{
        node.name    = {INPUT_NODE}
        node.passive = true
{capture_pin}      }}
      playback.props = {{
        node.name   = {OUTPUT_NODE}
        media.class = Audio/Source
      }}
    }}
  }}
]
"""


def write(state):
    os.makedirs(CONF_DIR, exist_ok=True)
    with open(CONF_PATH, "w") as f:
        f.write(generate(state))
    # drop the pre-rename fragment so the chain isn't defined twice
    if os.path.exists(STALE_CONF):
        os.unlink(STALE_CONF)


def parse_legacy(path=OLD_CONF):
    """Extract state from the legacy hand-written conf. Returns state or None."""
    if not os.path.exists(path):
        return None
    text = re.sub(r"#[^\n]*", "", open(path).read())
    state = default_state()

    m = re.search(r'node\.target\s*=\s*"([^"]+)"', text)
    if m:
        state["input"] = m.group(1)
    m = re.search(r'node\.description\s*=\s*"([^"]+)"', text)
    if m:
        # legacy descriptions carry a "(stages)" suffix; keep the base only
        state["source_desc"] = re.sub(r"\s*\([^()]*\)\s*$", "", m.group(1))

    known = {s: {p["port"]: p for p in STAGE_INFO[s]["params"]} for s in STAGES}
    for m in re.finditer(
            r'name\s*=\s*(\w+)[^{}]*?control\s*=\s*\{([^}]*)\}', text, re.S):
        name, body = m.group(1), m.group(2)
        if name not in known:
            continue
        state["stages"][name]["enabled"] = True
        for pm in re.finditer(r'"([^"]+)"\s+(-?[\d.]+)', body):
            port, val = pm.group(1), float(pm.group(2))
            if port in known[name]:
                state["stages"][name]["params"][port] = val
    if not any(st["enabled"] for st in state["stages"].values()):
        return None
    return state


def migrate():
    """One-time takeover of the legacy conf. Returns state or None."""
    state = parse_legacy()
    if state is None:
        return None
    os.rename(OLD_CONF, OLD_CONF + ".bak")
    return state
