"""Generate the WirePlumber software-DSP fragment from app state.

WirePlumber internal filter graphs attach the chain *inside* every
capture device node: clients keep seeing the real device node, with
the processing already applied. There is no virtual source, no device
pinning, no competition for the default source - whichever mic the
system default points at is filtered, including Bluetooth HFP mics
that appear and disappear at runtime. Mono capture nodes work too:
audioconvert adapts channels around the graph.
"""
import os

from catalog import STAGES, STAGE_INFO, default_state

WP_CONF_DIR = os.path.expanduser("~/.config/wireplumber/wireplumber.conf.d")
CONF_PATH = os.path.join(WP_CONF_DIR, "50-clearmic-dsp.conf")
OLD_CONF = os.path.expanduser(
    "~/.config/pipewire/pipewire.conf.d/20-rnnoise-source.conf")

# legacy fragments from the virtual-source era; must not coexist with
# the DSP rules or audio gets double-processed
LEGACY_CONFS = [
    "~/.config/pipewire/pipewire.conf.d/30-clearmic.conf",
    "~/.config/pipewire/pipewire.conf.d/30-clearmic.conf.bak",
    "~/.config/pipewire/pipewire.conf.d/30-clearmic.conf.disabled",
    "~/.config/pipewire/pipewire.conf.d/20-rnnoise-source.conf",
    "~/.config/pipewire/pipewire.conf.d/20-rnnoise-source.conf.bak",
    "~/.config/pipewire/pipewire.conf.d/30-mic-dsp-ui.conf",
]
LEGACY_CONFS = [os.path.expanduser(p) for p in LEGACY_CONFS]


def _num(v):
    v = float(v)
    if v.is_integer():
        return f"{v:.1f}"
    return f"{v:.6g}"


def generate(state):
    # autogain is parked (see main.py): LSP control ports break the
    # per-node param registration inside in-place graphs
    enabled = [s for s in STAGES
               if state["stages"][s]["enabled"] and s != "autogain"]
    nodes_txt = []
    for s in enabled:
        info = STAGE_INFO[s]
        ctrl = state["stages"][s]["params"]
        entries = ", ".join(
            f'"{p["port"]}" {_num(ctrl[p["port"]])}'
            for p in info["params"] if p["port"] in ctrl
        )
        control = f" control = {{ {entries} }}" if entries else ""
        nodes_txt.append(
            "            {\n"
            "              type = ladspa\n"
            f"              name = {s}\n"
            f'              plugin = "{info["plugin"]}"\n'
            f'              label = "{info["label"]}"{control}\n'
            "            }"
        )
    links_txt = []
    for a, b in zip(enabled, enabled[1:]):
        pa = STAGE_INFO[a]["audio"]
        pb = STAGE_INFO[b]["audio"]
        links_txt.append(
            f'            {{ output = "{a}:{pa["out_l"]}" input = "{b}:{pb["in_l"]}" }}\n'
            f'            {{ output = "{a}:{pa["out_r"]}" input = "{b}:{pb["in_r"]}" }}'
        )
    nodes_joined = "\n".join(nodes_txt)
    links_joined = "\n".join(links_txt)
    links_block = ""
    if links_txt:
        links_block = "          links = [\n" + links_joined + "\n          ]\n"
    return f"""\
# Generated by ClearMic. Manual edits will be overwritten.
node.filter-graph.rules = [
  {{
    matches = [
      {{ media.class = "Audio/Source"  node.name = "~alsa_input.*" }}
      {{ media.class = "Audio/Source"  node.name = "~bluez_input.*" }}
    ]
    actions = {{
      create-filter-graph = [
        {{
          nodes = [
{nodes_joined}
          ]
{links_block}        }}
      ]
    }}
  }}
]
"""


def write(state):
    os.makedirs(WP_CONF_DIR, exist_ok=True)
    with open(CONF_PATH, "w") as f:
        f.write(generate(state))
    # legacy fragments would double-process audio; remove them
    for p in LEGACY_CONFS:
        if os.path.exists(p):
            os.unlink(p)


def parse_legacy(path=OLD_CONF):
    """Extract state from the legacy hand-written conf. Returns state or None."""
    import re
    if not os.path.exists(path):
        return None
    text = re.sub(r"#[^\n]*", "", open(path).read())
    state = default_state()

    m = re.search(r'node\.target\s*=\s*"([^"]+)"', text)
    if m:
        state["input"] = m.group(1)
    known = {s: {p["port"]: p for p in STAGE_INFO[s]["params"]} for s in STAGES}
    for m in re.finditer(
            r'name\s*=\s*(\w+)[^{}]*?control\s*=\s*\{([^}]*)\}', text, re.S):
        name, body = m.group(1), m.group(2)
        if name not in known:
            continue
        state["stages"][name]["enabled"] = True
        for pm in re.finditer(r'"([^"]+)"\s+(-?[\d.]+)', body):
            port, val = pm.group(1), float(pm.group(2))
            if port in known[name]:
                state["stages"][name]["params"][port] = val
    if not any(st["enabled"] for st in state["stages"].values()):
        return None
    return state


def migrate():
    """One-time takeover of the legacy conf. Returns state or None."""
    state = parse_legacy()
    if state is None:
        return None
    os.rename(OLD_CONF, OLD_CONF + ".bak")
    return state
